server:
  port: 8080
spring:
  jackson:
    time-zone: UTC
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: validate
  application:
    name: training-tracker
  messages:
    basename: messages
logging:
  level:
    pl.akolata.trainingtracker: INFO

---
spring:
  profiles: sql-logger
  jpa:
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
---
spring:
  profiles: jpa-stats
  jpa:
    properties:
      hibernate:
        generate_statistics: true
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
      hibernate:
        stat: DEBUG
        engine:
          jdbc:
            batch:
              internal: ERROR
---
spring:
  profiles: jpa-debug
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
        transaction: DEBUG
      hibernate:
        engine: DEBUG
---
spring:
  profiles: local
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    driverClassName: org.h2.Driver
    username: sa
    password:
    platform: h2
    initialization-mode: embedded
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

app:
  jwt:
    secret: TT_JWT_SECRET
    token-expiration-in-ms: 604800000

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
---
spring:
  profiles: dev
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # add Flyway
  datasource:
    url: jdbc:postgresql://localhost:5432/training_tracker
    username: tt_user
    password: tt_password

app:
  jwt:
    secret: TT_JWT_SECRET_DEV
    token-expiration-in-ms: 604800000