GET http://localhost:8080/api/users/1/trainings?page=1&size=10&sort=id,ASC
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTgyOTI2ODgxLCJleHAiOjE1ODM1MzE2ODF9.OuqtFu5tQOKe2WML83fJjWfmJHedSP5dSunPw0NcbTv07Gue4_oSzWDjNG5FDyNEoBFzr44UbIDkmNRMJNOMSA

###